In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from tensorflow.keras.layers import Input, Dense, Conv2D, BatchNormalization, Activation, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras import activations
from tensorflow.keras.layers import Layer
from tensorflow.keras import layers
import tensorflow as tf

In [2]:
from Seq2Seq import clayers
from Seq2Seq import cactivations

In [3]:
tf.keras.backend.clear_session()
input_encoder = Input(shape=(299,30),name='encoder_input',dtype=tf.float64)
input_encoder2 = Input(shape=(18,),name='encoder_input1', dtype=tf.float64)
enc = clayers.BahdanauAttention(20)({'enocderHs':input_encoder, "decoderHt":input_encoder2})
ec = Model(inputs=[input_encoder,input_encoder2], outputs=enc,name="Encoder")

W0829 19:26:56.062106 19544 deprecation.py:506] From C:\Users\APPLIED AI\Anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [4]:
ec.summary()

Model: "Encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
encoder_input1 (InputLayer)     [(None, 18)]         0                                            
__________________________________________________________________________________________________
encoder_input (InputLayer)      [(None, 299, 30)]    0                                            
__________________________________________________________________________________________________
bahdanau_attention (BahdanauAtt ((None, 1, 30), (Non 1001        encoder_input1[0][0]             
                                                                 encoder_input[0][0]              
Total params: 1,001
Trainable params: 1,001
Non-trainable params: 0
__________________________________________________________________________________________________


In [5]:
lay = ec.layers[2]

In [6]:
lay.input_shape

{'enocderHs': (None, 299, 30), 'decoderHt': (None, 18)}

In [7]:
lay.trainable_weights

[<tf.Variable 'bahdanau_attention/bahdanau_attentionWa/kernel:0' shape=(18, 20) dtype=float64>,
 <tf.Variable 'bahdanau_attention/bahdanau_attentionUa/kernel:0' shape=(30, 20) dtype=float64>,
 <tf.Variable 'bahdanau_attention/bahdanau_attentionUa/bias:0' shape=(20,) dtype=float64>,
 <tf.Variable 'bahdanau_attention/bahdanau_attentionVa/kernel:0' shape=(20, 1) dtype=float64>,
 <tf.Variable 'bahdanau_attention/bahdanau_attentionVa/bias:0' shape=(1,) dtype=float64>]

In [8]:
enc_out = np.random.rand(1,299,30)
dec_time = np.random.rand(1,18)

In [9]:
pred = ec.predict([enc_out,dec_time])

In [10]:
pred[0]

array([[[0.46847242, 0.52131588, 0.52624267, 0.47991199, 0.49257776,
         0.51926419, 0.51109958, 0.48879396, 0.4811505 , 0.50310391,
         0.5176188 , 0.55013205, 0.54318154, 0.50026701, 0.48266005,
         0.52572615, 0.53378751, 0.51048531, 0.5137893 , 0.5065158 ,
         0.44587368, 0.5221608 , 0.50218066, 0.48748987, 0.46467854,
         0.47374507, 0.55339898, 0.46903254, 0.54923708, 0.46337889]]])

In [11]:
pred[1]

array([[[0.00608809],
        [0.00597161],
        [0.00287722],
        [0.00337029],
        [0.00265592],
        [0.00210088],
        [0.00252202],
        [0.00241118],
        [0.00370802],
        [0.0030037 ],
        [0.00459967],
        [0.00197777],
        [0.00230325],
        [0.0018521 ],
        [0.00328029],
        [0.00290602],
        [0.00340892],
        [0.00428554],
        [0.00372664],
        [0.00380746],
        [0.00295794],
        [0.00213594],
        [0.00245329],
        [0.00294017],
        [0.00428336],
        [0.0021236 ],
        [0.00237624],
        [0.00460721],
        [0.00330059],
        [0.00282156],
        [0.0034899 ],
        [0.00453992],
        [0.00354604],
        [0.00255882],
        [0.00301919],
        [0.00255568],
        [0.00342336],
        [0.00284301],
        [0.00518907],
        [0.00469493],
        [0.0036737 ],
        [0.00432879],
        [0.00497782],
        [0.0018269 ],
        [0.00304006],
        [0

In [12]:
z = np.random.rand(1,299)

In [13]:
mask = z>0.7

In [14]:
mask.shape

(1, 299)

In [15]:
input_encoder1 = Input(shape=(299,30),name='encoder_input1')
input_encoder21 = Input(shape=(18,),name='encoder_input11')
enc1 = clayers.BahdanauAttention(20, dropout_rate=0.5)({'enocderHs':input_encoder1, "decoderHt":input_encoder21}, mask= mask )
ec1 = Model(inputs=[input_encoder1,input_encoder21], outputs=enc1,name="Encoder1")

In [16]:
ec1.set_weights(ec.get_weights())

In [17]:
pred1 = ec1.predict([enc_out,dec_time])

In [18]:
pred1[0]

array([[[0.58171823, 0.58884138, 0.63167508, 0.59266423, 0.57352353,
         0.64137262, 0.61472036, 0.57511042, 0.54140157, 0.59140166,
         0.62866379, 0.62345499, 0.63262644, 0.57587823, 0.57890117,
         0.63011234, 0.6517398 , 0.58373807, 0.61133019, 0.60504147,
         0.53413561, 0.59826606, 0.61382586, 0.55741361, 0.56208113,
         0.61379471, 0.65811258, 0.5230791 , 0.64002367, 0.51780918]]])

In [21]:
pred[0]

array([[[0.46847242, 0.52131588, 0.52624267, 0.47991199, 0.49257776,
         0.51926419, 0.51109958, 0.48879396, 0.4811505 , 0.50310391,
         0.5176188 , 0.55013205, 0.54318154, 0.50026701, 0.48266005,
         0.52572615, 0.53378751, 0.51048531, 0.5137893 , 0.5065158 ,
         0.44587368, 0.5221608 , 0.50218066, 0.48748987, 0.46467854,
         0.47374507, 0.55339898, 0.46903254, 0.54923708, 0.46337889]]])

In [33]:
pred1[1]

array([[[0.00301616],
        [0.00810712],
        [0.00499735],
        [0.00687517],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.00482276],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.01093184],
        [0.        ],
        [0.00492609],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.00574892],
        [0.0044887 ],
        [0.        ],
        [0.00659918],
        [0.00267949],
        [0.        ],
        [0.00556889],
        [0.        ],
        [0.00745138],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.00794445],
        [0.00622469],
        [0.        ],
        [0.00459757],
        [0.        ],
        [0.00414036],
        [0.00719009],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.0078114 ],
        [0.00547404],
        [0.00926585],
        [0.        ],
        [0

In [269]:
class BahdanauAttention1(Layer):
    
    def __init__(self,units):
        
        super(BahdanauAttention1, self).__init__()

        self.Wa = layers.Dense(units)
        self.Ua = layers.Dense(units)
        self.Va = layers.Dense(1)
    
    def call(self, inputs):
    
        assert len(inputs) ==2, "inputs length must be 2 but got {}".format(len(inputs))

        enc_out, dec_prev_hs = inputs

        #assert len(enc_out.shape) == 3, "Encoder Hiddenstates/output should be 3 dim ( B x T x H ), but got {} dim".format(len(enc_out.shape))

        #assert len(dec_prev_hs.shape) == 2, "Decoder Hidden/output should be 2 dim (B x H), but got {} dim".format(len(dec_prev_hs.shape))
        
        # decprev_hs - Decoder hidden shape == (batch_size, hidden size)
        # hidden_with_time_axis shape == (batch_size, 1, hidden size)
        hidden_with_time_axis = tf.expand_dims(dec_prev_hs, 1)
        
        # score shape == (batch_size, max_length, 1)
        # we get 1 at the last axis because we are applying score to self.V
        # the shape of the tensor before applying self.V is (batch_size, max_length, units)
        score = self.Va(tf.nn.tanh(self.Wa(hidden_with_time_axis) + self.Ua(enc_out)))
        
        # attention_weights shape == (batch_size, max_length, 1)
        score = tf.squeeze(score,axis=2)
        
        attention_weights = tf.nn.softmax(score, axis=-1)
        
        # context_vector shape after sum == (batch_size, 1, hidden_size)
        #attention_weights = tf.squeeze(attention_weights,[2])
        #context_vector = attention_weights * enc_out
        context_vector = tf.tensordot(attention_weights, enc_out, axes=[1,1])
        
        #context_vector = tf.reduce_sum(context_vector, axis=1)
        #context_vector = tf.expand_dims(context_vector, 1)

        return context_vector 

In [270]:

input_encoder1 = Input(shape=(299,30),name='encoder_input1')
input_encoder21 = Input(shape=(18,),name='encoder_input11')
enc1 = BahdanauAttention1(20)([input_encoder1,input_encoder21])
ec1 = Model(inputs=[input_encoder1,input_encoder21], outputs=enc1,name="Encoder1")

In [271]:
ec1.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
encoder_input1 (InputLayer)     (None, 299, 30)      0                                            
__________________________________________________________________________________________________
encoder_input11 (InputLayer)    (None, 18)           0                                            
__________________________________________________________________________________________________
bahdanau_attention1_17 (Bahdana (None, None, 30)     1021        encoder_input1[0][0]             
                                                                 encoder_input11[0][0]            
Total params: 1,021
Trainable params: 1,021
Non-trainable params: 0
__________________________________________________________________________________________________


In [255]:
ec1.set_weights(ec.get_weights())

FailedPreconditionError: Error while reading resource variable bahdanau_attention/dense/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/bahdanau_attention/dense/kernel/class tensorflow::Var does not exist.
	 [[node bahdanau_attention/dense/kernel/Read/ReadVariableOp (defined at C:\Users\AAIC 2\AAIC\Seq2Seq\Layers.py:34) ]]

Caused by op 'bahdanau_attention/dense/kernel/Read/ReadVariableOp', defined at:
  File "C:\Users\AAIC 2\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\AAIC 2\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\AAIC 2\Anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\AAIC 2\Anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\AAIC 2\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2854, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in _run_cell
    return runner(coro)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-78-344da863ccf6>", line 4, in <module>
    enc = Layers.BahdanauAttention(20)([input_encoder,input_encoder2])
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\AAIC 2\AAIC\Seq2Seq\Layers.py", line 34, in call
    # decprev_hs - Decoder hidden shape == (batch_size, hidden size)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\core.py", line 949, in build
    trainable=True)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 349, in add_weight
    aggregation=aggregation)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 607, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_utils.py", line 145, in make_variable
    aggregation=aggregation)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2488, in default_variable_creator
    import_scope=import_scope)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 294, in __init__
    constraint=constraint)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 446, in _init_from_args
    value = self._read_variable_op()
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 728, in _read_variable_op
    self._dtype)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 549, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\AAIC 2\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Error while reading resource variable bahdanau_attention/dense/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/bahdanau_attention/dense/kernel/class tensorflow::Var does not exist.
	 [[node bahdanau_attention/dense/kernel/Read/ReadVariableOp (defined at C:\Users\AAIC 2\AAIC\Seq2Seq\Layers.py:34) ]]


In [136]:
dec_time.shape

(1, 18)

In [137]:
ec1.predict([enc_out,dec_time])

array([[[0.48155642, 0.4391204 , 0.49610093, 0.4956632 , 0.5051189 ,
         0.5419042 , 0.5046029 , 0.45739356, 0.5102644 , 0.5023593 ,
         0.5452222 , 0.5163187 , 0.48430276, 0.47160408, 0.5260588 ,
         0.49398088, 0.48618364, 0.5081909 , 0.51142097, 0.48695618,
         0.51736784, 0.50500995, 0.4929487 , 0.47522777, 0.52542967,
         0.49673676, 0.5032436 , 0.5038543 , 0.5095011 , 0.50547886]]],
      dtype=float32)

In [252]:
ec1.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
encoder_input1 (InputLayer)     (None, 299, 30)      0                                            
__________________________________________________________________________________________________
encoder_input11 (InputLayer)    (None, 18)           0                                            
__________________________________________________________________________________________________
bahdanau_attention1_11 (Bahdana (None, 1, 299, 30)   1021        encoder_input1[0][0]             
                                                                 encoder_input11[0][0]            
Total params: 1,021
Trainable params: 1,021
Non-trainable params: 0
__________________________________________________________________________________________________


In [6]:
from Seq2Seq.cactivations import softmax, hardmax

In [7]:
sess = tf.InteractiveSession()

In [8]:
x = tf.nn.softmax([2.,5.,3.])

In [9]:
sess.run(x)

array([0.04201007, 0.8437947 , 0.11419519], dtype=float32)

In [10]:
sess.run(softmax([2.,5.,3.]))

array([0.04201007, 0.8437947 , 0.11419519], dtype=float32)

In [19]:
t = np.random.rand(3,5,2)

In [20]:
t

array([[[0.02611115, 0.10637641],
        [0.32108248, 0.21443138],
        [0.19194634, 0.13275355],
        [0.91394329, 0.83391005],
        [0.50612032, 0.03669808]],

       [[0.68119429, 0.28752281],
        [0.98561268, 0.07282184],
        [0.97173626, 0.88691413],
        [0.26449125, 0.6861028 ],
        [0.17513496, 0.89407585]],

       [[0.87621288, 0.01600687],
        [0.95807974, 0.07338225],
        [0.15134578, 0.04977872],
        [0.01208139, 0.97130783],
        [0.8065923 , 0.21370335]]])

In [21]:
sess.run(hardmax(t))

array([[[0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.]]], dtype=float32)

In [199]:
test = sess.run(tf.one_hot(tf.math.argmax(t,-1),5))

In [200]:
tyy = sess.run(tf.nn.softmax(t))

In [201]:
test

array([[0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.]], dtype=float32)

In [203]:
t

array([[0.26509855, 0.70553496, 0.41480945, 0.71259458, 0.30775338],
       [0.93292848, 0.01112402, 0.10069279, 0.16851184, 0.64116961]])

In [188]:
tyy.shape

(2, 5, 1)

In [3]:
sess = tf.Session()

In [4]:
sess.run(tf.nn.softmax([1.,2.,3.]))

array([0.09003057, 0.24472848, 0.66524094], dtype=float32)

In [5]:
sess.run(cactivations.softmax([1., 2., 3.]))

array([0.09003057, 0.24472848, 0.66524094], dtype=float32)

In [6]:
zz = np.array([1.,2.,3.]) + np.array([0,1,0]) * -1e9

In [7]:
sess.run(tf.nn.softmax(zz))

array([0.11920292, 0.        , 0.88079708])

In [8]:
sess.run(cactivations.softmax(zz))

array([0.11920292, 0.        , 0.88079708])

In [9]:
sess.run(tf.contrib.sparsemax.sparsemax([[1.,2.,3.]]))

W0830 12:29:44.922322 19332 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0830 12:29:45.020347 19332 deprecation.py:323] From C:\Users\APPLIED AI\Anaconda3\lib\site-packages\tensorflow\contrib\sparsemax\python\ops\sparsemax.py:92: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


array([[0., 0., 1.]], dtype=float32)

In [10]:
sess.run(cactivations.sparsemax([[1.,2.,3.]]))

W0830 12:30:26.636062 19332 deprecation_wrapper.py:119] From D:\ML\TfKeras Custom Layers\Seq2Seq\cactivations.py:51: The name tf.is_nan is deprecated. Please use tf.math.is_nan instead.



array([[0., 0., 1.]], dtype=float32)

In [16]:
sess.run(tf.contrib.sparsemax.sparsemax(zz.reshape(1,3)))

array([[0., 0., 1.]])

In [11]:
test = np.random.random(size=(1,10)) * 5.4

In [12]:
test

array([[3.26730828, 0.04262891, 3.09585926, 4.90840568, 4.73109869,
        3.56666077, 3.33952132, 0.74360572, 2.42749901, 3.13652687]])

In [13]:
sess.run(tf.contrib.sparsemax.sparsemax(test))

array([[0.        , 0.        , 0.        , 0.58865349, 0.41134651,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [14]:
sess.run(cactivations.sparsemax(test))

array([[0.        , 0.        , 0.        , 0.58865349, 0.41134651,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [15]:
sess.run(cactivations.get('sparsemax')(test))

array([[0.        , 0.        , 0.        , 0.58865349, 0.41134651,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [31]:
test2 = test + np.array([[1, 1, 0, 0, 0, 1, 0, 0, 0, 1]]) * -1e9

In [32]:
test2

array([[-9.99999998e+08, -9.99999997e+08,  4.15061696e+00,
         5.37140344e+00,  2.39380946e+00, -9.99999997e+08,
         4.26024837e+00,  1.18268916e+00,  5.32399158e+00,
        -9.99999996e+08]])

In [33]:
sess.run(tf.contrib.sparsemax.sparsemax(test2))

array([[0.        , 0.        , 0.        , 0.52370593, 0.        ,
        0.        , 0.        , 0.        , 0.47629407, 0.        ]])

In [ ]:
cactivations.hardmax()

In [16]:
t = np.random.rand(1, 4, 1)

In [21]:
t2 = sess.run(tf.squeeze(t, 2))

In [22]:
t

array([[[0.37513276],
        [0.38091136],
        [0.45481904],
        [0.06901354]]])

In [24]:
t2.shape

(1, 4)

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 2.2, 4, 7])

In [3]:
num = 2.15

In [7]:
np.argmin((num - a)**2)

2

In [4]:
def get_least(a, num):
    

array([-1.15, -0.15,  0.05,  1.85,  4.85])