In [7]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [10]:
sess = tf.Session()

In [11]:
from Seq2Seq import clayers
from Seq2Seq import cactivations

In [37]:
probabilities = np.random.rand(4,10)

In [38]:
probabilities = probabilities.astype(np.float32)

In [39]:
attention_prev = np.random.randint(low=0, high=2, size=(4,10))

In [40]:
attention_prev = attention_prev.astype(np.float32)

In [41]:
z = clayers._monotonic_attetion(probabilities, attention_prev, 'parallel')

In [42]:
out = sess.run(z)

In [43]:
out

array([[0.        , 0.5096693 , 0.32174817, 0.26419935, 0.4364667 ,
        0.14709371, 0.147333  , 0.0484388 , 0.10808603, 0.7087337 ],
       [0.6622465 , 0.6009374 , 0.09691039, 0.15517266, 1.3573459 ,
        0.6376775 , 0.26808342, 0.7171332 , 0.30650726, 0.26418272],
       [0.69173044, 0.20733161, 0.7777227 , 0.19574535, 0.99411315,
        0.7962346 , 0.73440015, 0.18242632, 0.39184526, 0.5438453 ],
       [0.        , 0.        , 0.        , 0.7223142 , 0.16316107,
        1.6747235 , 0.6424424 , 0.60608673, 0.01293936, 0.01287453]],
      dtype=float32)

In [44]:
out2 = tf.contrib.seq2seq.monotonic_attention(probabilities, attention_prev, 'parallel')

In [45]:
out2 = sess.run(out2)

In [55]:
np.any(out2 != out)

False

In [18]:
mask = np.array([ True ,True ,True , True , False ,False])

In [14]:
val = [1., 2., 3., 4., 6., 7.]

In [15]:
sess.run(tf.nn.softmax(val))

array([0.00171516, 0.0046623 , 0.01267344, 0.03444998, 0.2545528 ,
       0.69194627], dtype=float32)

In [19]:
score = val + mask*-1e9

In [20]:
score

array([-9.99999999e+08, -9.99999998e+08, -9.99999997e+08, -9.99999996e+08,
        6.00000000e+00,  7.00000000e+00])

In [21]:
def create_padding_mask(x):
    mask = tf.cast(tf.math.equal(x, 0), tf.float32)
    # (batch_size, 1, 1, sequence length)
    return mask

In [23]:
sess.run(create_padding_mask(tf.cast(mask,tf.float32)))

array([0., 0., 0., 0., 1., 1.], dtype=float32)

In [24]:
casttt = tf.cast(mask, tf.float32)

In [26]:
sess.run(tf.not(casttt))

SyntaxError: invalid syntax (<ipython-input-26-23d056ab744c>, line 1)

In [27]:
casttt

<tf.Tensor 'Cast_2:0' shape=(6,) dtype=float32>

In [31]:
casttt = tf.cast(tf.math.equal(mask, False), tf.float32)

In [35]:
sess.run(tf.nn.softmax(val+casttt*-1e9))

array([0.0320586 , 0.08714432, 0.23688284, 0.6439143 , 0.        ,
       0.        ], dtype=float32)

In [36]:
mask

array([ True,  True,  True,  True, False, False])

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from tensorflow.keras.layers import Input, Dense, Conv2D, BatchNormalization, Activation, Dropout, GRU, Embedding
from tensorflow.keras.models import Model
from tensorflow.keras import activations
from tensorflow.keras.layers import Layer
from tensorflow.keras import layers
import tensorflow as tf

In [7]:
from tensorflow.keras.layers import Input, Dense, Conv2D, BatchNormalization, Activation, Dropout, GRU, Embedding, LSTM,SimpleRNN

In [8]:
tf.keras.backend.clear_session()
def encoder():
    input_encoder = Input(shape=(12,), name='encoder_input')

    x_embedded = Embedding(input_dim=500, output_dim=32, input_length=12,
                           mask_zero=False, name="embedding_layer_encoder")(input_encoder)
    
    gru_output = SimpleRNN(200,use_bias=False,name="Encoder_GRU")(x_embedded)
    x_out = Dense(10, activation='softmax', use_bias=False)(gru_output)
    
    return Model(inputs=input_encoder, outputs=x_out)

In [9]:
ec = encoder()

In [10]:
ec.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
encoder_input (InputLayer)   [(None, 12)]              0         
_________________________________________________________________
embedding_layer_encoder (Emb (None, 12, 32)            16000     
_________________________________________________________________
Encoder_GRU (SimpleRNN)      (None, 200)               46400     
_________________________________________________________________
dense (Dense)                (None, 10)                2000      
Total params: 64,400
Trainable params: 64,400
Non-trainable params: 0
_________________________________________________________________


In [11]:
48400+16000

64400